
NAME		=	phonebook

CC			=	clang++

FLAGS		=	-Wall -Werror -Wextra

SRC			=	ClassContact.cpp phone_book.cpp tools.cpp

INC			=	ClassContact.hpp phone_book.hpp

all			:	$(NAME)

$(NAME)		:
				$(CC) $(FLAGS) $(SRC) -o $(NAME)

fclean		:
				rm -rf $(NAME)