
NAME		=	replace

CC			=	clang++

FLAGS		=	-Wall -Wextra

SRC			=	main.cpp

all			:	$(NAME)

$(NAME)		:
				$(CC) $(FLAGS) $(SRC) -o $(NAME)

fclean		:
				rm -rf $(NAME)
				rm -rf *.replace

re			:	fclean all
